---
version: 2.1

executors:
  default:
    docker:
      - image: quay.io/hemanth22/rockylinux9-ansible:9

jobs:
  build:
    executor: default
    steps:
      - checkout
      - run:
          name: Python pip installation
          command: |
            dnf install python311 alternatives wget -y
            alternatives --install /usr/bin/python3 python3 /usr/bin/python3.11 1

      - run:
          name: Print Python Verson
          command: |
            python3 -V

      - run:
          name: Provision Pip modules
          command: |
            python3.11 -m ensurepip --upgrade --user
            python3 -m pip install requests --user
      - run:
          name: Provision Ansible modules
          command: |
            python3 -m pip install ansible ansible-lint ansible-core molecule yamllint --user
      - run:
          name: Yamllint code execution
          command: |
            yamllint .
      - run:
          name: ansible-lint code execution
          command: |
            ansible-lint . | tee >> ansible_lint_error.txt

workflows:
  ansible_app:
    jobs:
      - build
