---
version: 2.1

executors:
  default:
    docker:
      - image: quay.io/hemanth22/rockylinux9-ansible:926f48508423dbad441247aff00aa4bbe5783399

jobs:
  build:
    executor: default
    steps:
      - checkout
      - run:
          name: Python pip installation
          command: |
            dnf install python311 alternatives wget bash -y
            alternatives --install /usr/bin/python3 python3 /usr/bin/python3.11 1

      - run:
          name: Print Python Pip Verson
          command: |
            python3 -V

      - run:
          name: Provision Pip modules
          command: |
            python3.11 -m ensurepip --upgrade --user
            python3 -m pip install --upgrade pip
            python3 -m pip install requests --user

      - run:
          name: Print Python Verson
          command: |
            pip -V

      - run:
          name: Setup Bash Profile
          command: |
            echo 'export PATH=$PATH:~/.local/bin' > ~/.bash_profile
            echo 'alias ll="ls -la"' > ~/.bashrc
            echo 'source ~/.bash_profile' >> ~/.bashrc
            echo $PATH

      - run:
          name: Verify Bash Profile
          command: ls -ltra

      - run:
          name: Provision Ansible modules
          command: |
            python3 -m pip install ansible ansible-lint ansible-core molecule yamllint --user
      - run:
          name: Yamllint code execution
          command: |
            yamllint .
      - run:
          name: ansible-lint code execution
          command: |
            ansible-lint . | tee >> ansible_lint_error.txt

workflows:
  ansible_app:
    jobs:
      - build
